// Autogenerated from Pigeon (v29.0.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

/// One native death from a previous run, as the OS remembers it.
class NativeCrashReport {
  NativeCrashReport({
    required this.id,
    required this.kind,
    required this.timestampMicros,
    this.type,
    this.message,
    this.stacktrace,
    this.threads,
    this.sessionId,
    this.attributes,
  });

  /// The platform's own identifier for this record, opaque to Dart. It is
  /// what [NativeCrashApi.acknowledge] takes, and it must be stable across
  /// launches so a report is acknowledged exactly once.
  String id;

  /// One of `jvm`, `native`, `anr`, `nsexception`, `signal`, `hang`.
  ///
  /// A string rather than an enum so an unknown future value from a newer OS
  /// arrives intact instead of failing the whole call.
  String kind;

  /// When the process died, in microseconds since the Unix epoch.
  int timestampMicros;

  /// The platform's classification: the signal name, the exception class, the
  /// exit reason.
  String? type;

  /// The human-readable reason, where the platform keeps one.
  String? message;

  /// The stack trace, already symbolised as far as the OS got.
  String? stacktrace;

  /// Per-thread frames for a crash whose stack is only meaningful per thread.
  List<String>? threads;

  /// The app session the death happened in, where the OS groups by one.
  String? sessionId;

  /// Anything else the platform knows, flattened.
  Map<String, String>? attributes;

  List<Object?> _toList() {
    return <Object?>[
      id,
      kind,
      timestampMicros,
      type,
      message,
      stacktrace,
      threads,
      sessionId,
      attributes,
    ];
  }

  Object encode() {
    return _toList();
  }

  static NativeCrashReport decode(Object result) {
    result as List<Object?>;
    return NativeCrashReport(
      id: result[0]! as String,
      kind: result[1]! as String,
      timestampMicros: result[2]! as int,
      type: result[3] as String?,
      message: result[4] as String?,
      stacktrace: result[5] as String?,
      threads: (result[6] as List<Object?>?)?.cast<String>(),
      sessionId: result[7] as String?,
      attributes: (result[8] as Map<Object?, Object?>?)?.cast<String, String>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeCrashReport || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) &&
        _deepEquals(kind, other.kind) &&
        _deepEquals(timestampMicros, other.timestampMicros) &&
        _deepEquals(type, other.type) &&
        _deepEquals(message, other.message) &&
        _deepEquals(stacktrace, other.stacktrace) &&
        _deepEquals(threads, other.threads) &&
        _deepEquals(sessionId, other.sessionId) &&
        _deepEquals(attributes, other.attributes);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeCrashReport(id: $id, kind: $kind, timestampMicros: $timestampMicros, type: $type, message: $message, stacktrace: $stacktrace, threads: $threads, sessionId: $sessionId, attributes: $attributes)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is NativeCrashReport) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return NativeCrashReport.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Reads and acknowledges the previous run's native deaths.
class NativeCrashApi {
  /// Constructor for [NativeCrashApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  NativeCrashApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';

  final BinaryMessenger? pigeonVar_binaryMessenger;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Every report the OS holds that has not been acknowledged yet, oldest
  /// first.
  ///
  /// The OS's list cannot be cleared, so the platform side deduplicates by a
  /// persisted watermark; Dart only ever sees the reports that are new to it.
  Future<List<NativeCrashReport>> pending() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.otel_zone.NativeCrashApi.pending$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>).cast<NativeCrashReport>();
  }

  /// Marks [ids] as delivered.
  ///
  /// Called only once the reports are durable, so that an unreachable
  /// collector leaves them to be re-read on the next launch rather than
  /// dropping them.
  Future<void> acknowledge(List<String> ids) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.otel_zone.NativeCrashApi.acknowledge$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[ids],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }
}
