// Autogenerated from Pigeon (v29.0.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>"))"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum NativeCrashApiPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// One native death from a previous run, as the OS remembers it.
///
/// Generated class from Pigeon that represents data sent in messages.
struct NativeCrashReport: Hashable, CustomStringConvertible {
  /// The platform's own identifier for this record, opaque to Dart. It is
  /// what [NativeCrashApi.acknowledge] takes, and it must be stable across
  /// launches so a report is acknowledged exactly once.
  var id: String
  /// One of `jvm`, `native`, `anr`, `nsexception`, `signal`, `hang`.
  ///
  /// A string rather than an enum so an unknown future value from a newer OS
  /// arrives intact instead of failing the whole call.
  var kind: String
  /// When the process died, in microseconds since the Unix epoch.
  var timestampMicros: Int64
  /// The platform's classification: the signal name, the exception class, the
  /// exit reason.
  var type: String? = nil
  /// The human-readable reason, where the platform keeps one.
  var message: String? = nil
  /// The stack trace, already symbolised as far as the OS got.
  var stacktrace: String? = nil
  /// Per-thread frames for a crash whose stack is only meaningful per thread.
  var threads: [String]? = nil
  /// The app session the death happened in, where the OS groups by one.
  var sessionId: String? = nil
  /// Anything else the platform knows, flattened.
  var attributes: [String: String]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeCrashReport? {
    let id = pigeonVar_list[0] as! String
    let kind = pigeonVar_list[1] as! String
    let timestampMicros = pigeonVar_list[2] as! Int64
    let type: String? = nilOrValue(pigeonVar_list[3])
    let message: String? = nilOrValue(pigeonVar_list[4])
    let stacktrace: String? = nilOrValue(pigeonVar_list[5])
    let threads: [String]? = nilOrValue(pigeonVar_list[6])
    let sessionId: String? = nilOrValue(pigeonVar_list[7])
    let attributes: [String: String]? = nilOrValue(pigeonVar_list[8])

    return NativeCrashReport(
      id: id,
      kind: kind,
      timestampMicros: timestampMicros,
      type: type,
      message: message,
      stacktrace: stacktrace,
      threads: threads,
      sessionId: sessionId,
      attributes: attributes
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      kind,
      timestampMicros,
      type,
      message,
      stacktrace,
      threads,
      sessionId,
      attributes,
    ]
  }
  static func == (lhs: NativeCrashReport, rhs: NativeCrashReport) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return NativeCrashApiPigeonInternal.deepEquals(lhs.id, rhs.id) && NativeCrashApiPigeonInternal.deepEquals(lhs.kind, rhs.kind) && NativeCrashApiPigeonInternal.deepEquals(lhs.timestampMicros, rhs.timestampMicros) && NativeCrashApiPigeonInternal.deepEquals(lhs.type, rhs.type) && NativeCrashApiPigeonInternal.deepEquals(lhs.message, rhs.message) && NativeCrashApiPigeonInternal.deepEquals(lhs.stacktrace, rhs.stacktrace) && NativeCrashApiPigeonInternal.deepEquals(lhs.threads, rhs.threads) && NativeCrashApiPigeonInternal.deepEquals(lhs.sessionId, rhs.sessionId) && NativeCrashApiPigeonInternal.deepEquals(lhs.attributes, rhs.attributes)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeCrashReport")
    NativeCrashApiPigeonInternal.deepHash(value: id, hasher: &hasher)
    NativeCrashApiPigeonInternal.deepHash(value: kind, hasher: &hasher)
    NativeCrashApiPigeonInternal.deepHash(value: timestampMicros, hasher: &hasher)
    NativeCrashApiPigeonInternal.deepHash(value: type, hasher: &hasher)
    NativeCrashApiPigeonInternal.deepHash(value: message, hasher: &hasher)
    NativeCrashApiPigeonInternal.deepHash(value: stacktrace, hasher: &hasher)
    NativeCrashApiPigeonInternal.deepHash(value: threads, hasher: &hasher)
    NativeCrashApiPigeonInternal.deepHash(value: sessionId, hasher: &hasher)
    NativeCrashApiPigeonInternal.deepHash(value: attributes, hasher: &hasher)
  }

  public var description: String {
    return "NativeCrashReport(id: \(String(describing: id)), kind: \(String(describing: kind)), timestampMicros: \(String(describing: timestampMicros)), type: \(String(describing: type)), message: \(String(describing: message)), stacktrace: \(String(describing: stacktrace)), threads: \(String(describing: threads)), sessionId: \(String(describing: sessionId)), attributes: \(String(describing: attributes)))"
  }
}

private class NativeCrashApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return NativeCrashReport.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class NativeCrashApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? NativeCrashReport {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class NativeCrashApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return NativeCrashApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return NativeCrashApiPigeonCodecWriter(data: data)
  }
}

class NativeCrashApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = NativeCrashApiPigeonCodec(readerWriter: NativeCrashApiPigeonCodecReaderWriter())
}


/// Reads and acknowledges the previous run's native deaths.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol NativeCrashApi {
  /// Every report the OS holds that has not been acknowledged yet, oldest
  /// first.
  ///
  /// The OS's list cannot be cleared, so the platform side deduplicates by a
  /// persisted watermark; Dart only ever sees the reports that are new to it.
  func pending() async throws -> [NativeCrashReport]
  /// Marks [ids] as delivered.
  ///
  /// Called only once the reports are durable, so that an unreachable
  /// collector leaves them to be re-read on the next launch rather than
  /// dropping them.
  func acknowledge(ids: [String]) async throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class NativeCrashApiSetup {
  static var codec: FlutterStandardMessageCodec { NativeCrashApiPigeonCodec.shared }
  /// Sets up an instance of `NativeCrashApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: NativeCrashApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Every report the OS holds that has not been acknowledged yet, oldest
    /// first.
    ///
    /// The OS's list cannot be cleared, so the platform side deduplicates by a
    /// persisted watermark; Dart only ever sees the reports that are new to it.
    let pendingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.otel_zone.NativeCrashApi.pending\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pendingChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            let result = try await api.pending()
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      pendingChannel.setMessageHandler(nil)
    }
    /// Marks [ids] as delivered.
    ///
    /// Called only once the reports are durable, so that an unreachable
    /// collector leaves them to be re-read on the next launch rather than
    /// dropping them.
    let acknowledgeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.otel_zone.NativeCrashApi.acknowledge\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      acknowledgeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idsArg = args[0] as! [String]
        Task { @MainActor in
          do {
            try await api.acknowledge(ids: idsArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      acknowledgeChannel.setMessageHandler(nil)
    }
  }
}
