import Flutter
import UIKit

@main
@objc class AppDelegate: FlutterAppDelegate, FlutterImplicitEngineDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    #if DEBUG
      CrashHarness.crashIfLaunchedWithRequest()
    #endif
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }

  func didInitializeImplicitFlutterEngine(_ engineBridge: FlutterImplicitEngineBridge) {
    GeneratedPluginRegistrant.register(with: engineBridge.pluginRegistry)
    #if DEBUG
      CrashHarness.register(messenger: engineBridge.applicationRegistrar.messenger())
    #endif
  }
}

// The crash harness is compiled into Debug builds only. `ios/Flutter/Debug.xcconfig`
// defines DEBUG for the Debug configuration (Flutter's template does not), and
// Release and Profile do not define it, so none of this — the channel name, the
// exception text, the launch argument — is in their binary. It lives in this
// file rather than a new one because the runner project is generated by
// `flutter create` (only this file is committed), so a new file would not be
// in the Xcode project.
#if DEBUG
  /// Induces each way an iOS process can die, so crash capture can be
  /// exercised on purpose.
  ///
  /// Two doors lead here, and both end in `crash(kind:)`:
  ///  - the `otel_zone_example/crash` method channel, for the debug UI;
  ///  - a launch argument, for a host script that cannot reach a running
  ///    process: `xcrun simctl launch <device> <bundle> -otel_crash nsexception`
  ///    (UserDefaults reads `-key value` launch arguments).
  enum CrashHarness {
    static let channel = "otel_zone_example/crash"
    static let argument = "otel_crash"
    static let kinds: Set<String> = ["nsexception", "signal"]

    /// How long after launch a requested crash fires, so the engine has
    /// registered the plugins (and with them the NSException handler) and the
    /// previous run's crash has been drained first.
    static let launchDelaySeconds = 4.0

    static func register(messenger: FlutterBinaryMessenger) {
      FlutterMethodChannel(name: channel, binaryMessenger: messenger)
        .setMethodCallHandler { call, result in
          guard call.method == "crash" else { return result(FlutterMethodNotImplemented) }
          guard let kind = call.arguments as? String, kinds.contains(kind) else {
            return result(
              FlutterError(
                code: "unknown-kind", message: "Unknown crash kind: \(String(describing: call.arguments))",
                details: Array(kinds)))
          }
          crash(kind: kind, after: 0.3)
          result(nil)
        }
    }

    static func crashIfLaunchedWithRequest() {
      guard let kind = UserDefaults.standard.string(forKey: argument) else { return }
      guard kinds.contains(kind) else {
        NSLog("OtelZoneCrashHarness: unknown crash kind '%@'", kind)
        return
      }
      crash(kind: kind, after: launchDelaySeconds)
    }

    /// Posted, never run inline: a channel handler that raised would be inside
    /// the engine's own call, and the crash should look like the app's, not
    /// the channel's.
    static func crash(kind: String, after delay: TimeInterval) {
      NSLog("OtelZoneCrashHarness: crashing on purpose: %@", kind)
      DispatchQueue.main.asyncAfter(deadline: .now() + delay) {
        switch kind {
        case "nsexception":
          NSException(
            name: NSExceptionName("OtelZoneHarnessException"),
            reason: "otel_zone harness: induced NSException", userInfo: nil
          ).raise()
        default:
          // SIGABRT, the signal `abort()` raises and the one an uncaught
          // exception ends in.
          raise(SIGABRT)
        }
      }
    }
  }
#endif
